 [package]
name = "dota_usermessages" 
version = "0.1.0" 

[dependencies] 
protobuf = "1.4.1"
networkbasetypes = { path = "../networkbasetypes" }
dota_commonmessages = { path = "../dota_commonmessages" }
